# xRay
#
# Thanks for downloading xRay!
# If the plugin doesn't work, make sure to contact me on my Discord: https://discord.gg/zgKr2YM

Messages:
  NotAPlayer: '&8&oxRay: &7You need to be a player to execute this command!'
  NoPermission: '&&8&oxRay: &7You dont have permissions to execute this command'
  UnknownArgument: '&8&oxRay: &7The argument you specified seems to be incorrect!'
  DisabledxRay: '&8&oxRay: &7Disabled xRay vision'
  EnabledxRay: '&8&oxRay: &7Enabled xRay vision'
  Reloaded: '&8&oxRay: &7Reloaded the plugin!'
  AddedBlock: '&8&oxRay: &7Added block!'
  RemovedBlock: '&8&oxRay: &7Removed block!'
  UnknownBlock: '&8&oxRay: &7The block you specified is unknown!'
  AlreadyAdded: '&8&oxRay: &7This block is already affected by the xRay vision'
  DoesntExist: '&8&oxRay: &7This block is not affected by the xRay vision'

Settings:
  UpdateDelay: 5
  # How long should the plugin wait to update the xRay vision? (In seconds)
  xRayBlocks:
      - 'COAL_ORE'
      - 'IRON_ORE'
      - 'GOLD_ORE'
      - 'DIAMOND_ORE'
      - 'WOOD'
      - 'WATER'
      - 'LAVA'
      - 'STATIONARY_WATER'
      - 'STATIONARY_LAVA'
      - 'BEDROCK'
  Mode: CHUNK # CHUNK / BLOCK
  Range: 3
  # Range of the xRay (In chunks)